### ISSUE TITLE
Get "Error: [jqLite:onargs] http://errors.angularjs.org/1.3.6/jqLite/onargs     at Error (native)" 

### ISSUE THREAD

**Issue by antonrao** [bvaughn/angular-form-for#104]
Hello, @bvaughn

I make a test code on jsfiddle (http://jsfiddle.net/naolin2008/96s81Lt7/1/) .  if it doesn't load Jquery 2.1.3 , it  will return an error  "Error: [jqLite:onargs] http://errors.angularjs.org/1.3.6/jqLite/onargs at Error (native)". but it is work fine if it load jquery].  Is JQuery required on v3.0.3?  Could you help to review this issue.

**Comment by bvaughn** [comment]
Looks like the JS generated by TypeScript uses the long-form, jQuery-only style of `on()` (with `selector`) even though this isn't necessary... I'll fix this and build a 3.0.4 release when I get home from work this evening.

Thanks for pointing it out and for the nice JS fiddle. :)

**Comment by wlingke** [comment]
+1 also having trouble with this. When will an update be pushed out?

**Comment by bvaughn** [comment]
When I get home from work this evening :)

**Comment by wlingke** [comment]
Awesome looking forward to it. This is a great library by the way! I'm really glad you put this together.

**Comment by bvaughn** [comment]
This issue has been resolved in [version 3.0.4](https://github.com/bvaughn/angular-form-for/releases/tag/3.0.4).

Here's an updated version of your fiddle showing the fix: http://jsfiddle.net/bvaughn/96s81Lt7/3/

I've also [filed an issue](https://github.com/seanhess/angularjs-typescript/issues/2) and [posted a PR](https://github.com/seanhess/angularjs-typescript/pull/3) to resolve the bad TypeScript jQuery definitions file that I patched in order to submit this fix.

Thanks for reporting it!
