### ISSUE TITLE
Help Icon "defaults" to Font Awesome

### ISSUE THREAD

**Issue by Skovy** [bvaughn/angular-form-for#131]
**Help:** *Optional help tooltip to display on hover. By default this makes use of the Angular Bootstrap tooltip directive and the Font Awesome icon set.* - [formFor Docs](http://bvaughn.github.io/angular-form-for/#/documentation/textField)

Does this mean I can change it so it uses the Bootstrap Glyphicon set? I browsed the source and it looked as if Font Awesome was hard-coded into the help option icon. I would be willing to create the functionality to choose between Font Awesome or Bootstrap. What is the intended functionality? Thanks!

**Comment by bvaughn** [comment]
Hi @Skovy,

formFor actually makes it pretty easy for you to override templates. (See [template overrides](http://bvaughn.github.io/angular-form-for/#/demo/template-overrides).) They're broken down into relatively small sub-templates so you can override things like the label icon easily.

For instance, to customize the help icon you could just override the [field-label.html](https://github.com/bvaughn/angular-form-for/blob/master/templates/bootstrap/field-label.html) template. Name it `field-label.html` and make sure it's located in a `form-for/templates/` directory. This would definitely be the fastest and easiest solution for you.

Alternately we could add in support for customizing the icon- perhaps using the [FormForConfiguration](http://bvaughn.github.io/angular-form-for/#/documentation/FormForConfiguration) object, since this configuration would span all form controls.

What are your thoughts on either approach? Pull requests are welcome!

**Comment by bvaughn** [comment]
Ping @Skovy :)

**Comment by hutzelknecht** [comment]
Although FontAwesome is more "awesome" often glyphicons are in the app already, which wouldn't justify including another icon set - for bandwidth reasons perhaps. I would find a new formForConfiguration helpful. But would it be enough just to add a switch between the two. The templates would need adjustment wouldn't they?

**Comment by bvaughn** [comment]
Yes, if we added a configuration option to FormForConfiguration we would
also need to modify the label template.

**Comment by Skovy** [comment]
It was just a thought because I personally prefer Font Awesome and wanted to quickly change the help icon without overriding. I would be willing to make a pull request if this enhancement makes sense!

**Comment by bvaughn** [comment]
I think it makes sense. It would only require a couple of updates:
* `FormForConfiguration` to expose the new setting
* `FieldLabelDirective` to read the new option and set a `$scope` property
* `field-label.html` template to bind to the new `$scope` property

And then of course the `FormForConfiguration` docs would need an update in the `gh-pages` branch.

If you'd be willing to do this @Skovy, I'd love to get another person contributing as my time is sometimes very limited. But I'd be willing to do it also since it seems like a small enough change.

**Comment by Skovy** [comment]
@bvaughn I will give it a shot and get your feedback!

**Comment by bvaughn** [comment]
@Skovy was awesome enough to implement this in r140. I'm going to update `gh-pages` documentation to mention the new configuration option and then I'll make a release.

**Comment by bvaughn** [comment]
This just went out in release [4.0.6](https://github.com/bvaughn/angular-form-for/releases/tag/4.0.6)
