### ISSUE TITLE
update is misspelled

### ISSUE THREAD

**Issue by lookfirst** [bvaughn/angular-form-for#137]
https://github.com/bvaughn/angular-form-for/blob/master/source/utils/promise-utils.ts#L67

update is misspelled

i'd submit a PR, but i'm not sure what other code is affected by this. =)

**Comment by bvaughn** [comment]
Whoops :) Fixed. It's just an internal function so it won't affect anything.

**Comment by lookfirst** [comment]
Yea. Super minor. Was reading the code so I figured I'd point it out.

Also, I noticed that you don't declare the 'import' reference comment headers at the top of all the files. Idea marks all sorts of code in red because of that. Why not declare them?

**Comment by bvaughn** [comment]
No worries :) It's easy to fix stuff like that so I don't mind.

I'm not sure what you mean by the latter. Declaring a reference and importing are different things. I declare references to things like Angular because formFor requires the to run- and I'd like TypeScript to provide static type-checking for me- but I don't need Angular to build or be part of the formFor dist.

I'm not seeing any errors in WebStorm so I'm not sure what you're seeing in Idea. Give me an example?
