### ISSUE TITLE
Select field not pre-selecting value when label and value are equal

### ISSUE THREAD

**Issue by corystevens** [bvaughn/angular-form-for#145]
This is a strange edge case that I've stumbled on.  When the data backing a select field has the same value for the value-attribute and label-attribute, the select field doesn't get selected.  

I've made a plunker to demonstrate this http://plnkr.co/edit/P3y37DpCicnK3WHHjAfT?p=preview 

Whats also strange, both options are selected in the html.  If I use the template changes that you made a few days ago, changing the select to use an ng-repeat, it works fine.  If I upgrade Angular to 1.4.x, it also works.

**Comment by bvaughn** [comment]
Oh boy. So this is another issue that's only for certain versions of Angular huh? :)

Thanks for filing it and for providing the plunker. I'll try to take a look at it when I get the time. Hopefully soon! No promises though, if there's an underlying Angular issue. Select menus are pretty tricky already so I'm a little wary of introducing any version-specific hacks. :)

**Comment by bvaughn** [comment]
You're right. It's interesting to see that the right `<option>` is marked as selected, and even shows as selected when the `<select>` menu is opened...but the label isn't shown when its closed.

**Comment by bvaughn** [comment]
This issue seems to have been reported by others:
• http://stackoverflow.com/questions/27970971/bug-when-value-and-label-of-ng-options-are-equivalent

Playing a little more I see that this was a regression in Angular 1.3. Your plunker works correctly for Angular 1.2 and 1.4 but breaks for 1.3. 1.3 has some other problems that have bitten me too (like [this one](https://github.com/angular/angular.js/issues/9714)).

I'm pretty sure I'm not going to try fixing this on the formFor side. It's edge-casey and seems likely to require some nasty hacking.

**Comment by bvaughn** [comment]
Thought about this a bit more and I've decided I'm not going to patch select to work around an edge-case Angular bug. I appreciate your help in finding this- particularly the excellent Plunker example.

**Comment by corystevens** [comment]
Thanks for looking into this.  We have a workaround on our end thats sufficient until we upgrade to 1.4.

**Comment by bvaughn** [comment]
No problem. I'm glad you've got a work around. Sorry I wasn't able to provide more help on this end. :)
