### ISSUE TITLE
Checkbox Fix Release

### ISSUE THREAD

**Issue by sgrady** [bvaughn/angular-form-for#161]
Hi, I noticed the issue with your last release and how true/false is being set on your checkboxes. Based on your last commit - you fixed this in master. I was curious when you intend to tag/release that fix? We need it for the project I am working on.

**Comment by bvaughn** [comment]
Hi @sgrady,

I've fallen really behind on this project because of my day job. (I joined a startup recently and it's taking the majority of my focus.) You are correct that a release is all that's needed to address this issue.

I've just created [release `4.1.4`](https://github.com/bvaughn/angular-form-for/releases/tag/4.1.4) which contains several nice additions by @indrimuska
