### ISSUE TITLE
Required validation of objects with initial values

### ISSUE THREAD

**Issue by palodelincak** [bvaughn/angular-form-for#93]
Hello, I'm not sure if this is a bug, but it's not expected behaviour so I'm going to submit this issue.

I made Plunker:
http://plnkr.co/edit/E7Epb1deham2TDLkdEEV?p=preview

There is test object with initial value `0` and once you click `Save` without modifying this value you'll get `Required field` validation message. But once you'll go and modify this value from `0` to `10` and then back to `0` and you'll hit `Save` - validation message is not present.

I had also issues with validation of checkbox values (I know, it doesn't make sense to validate checkboxes - but this attribute/field may have multiple types - string, booleans...). And I think this is similiar because `0` is considered as false.

**Comment by bvaughn** [comment]
This sounds like a bug, although kind of an edge-case one. It's probably something to do with 0 being treated as an unset value in one place and then being evaluated as a non-null value in another.

I'll add it to the queue of things for a subsequent release, but I might not get to it too quickly because it seems kind of low-priority and I'm currently distracted by [Task Runner](https://github.com/bvaughn/task-runner). ;)

In the meanwhile, feel free to submit a patch if you have ideas for a fix!

**Comment by bvaughn** [comment]
Hi again @palodelincak. Thanks for submitting the Plunker with this bug report. That helps. :)

I've resolved this issue in the `type-script` branch and will be releasing the fix once I've completed regression testing the newly rewritten formFor (to make sure it's fully backwards compatible). :)

**Comment by bvaughn** [comment]
Just released 2.0.0 which contains this fix.

**Comment by palodelincak** [comment]
Thanks! Works like a charm!

BTW: Sorry I was not able to take a look at this sooner.

**Comment by bvaughn** [comment]
Happy it worked for you. No problem :)
